# Generated by Django 5.2.9 on 2026-01-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_bio_user_name_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avtar',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
