# Generated by Django 5.2.9 on 2026-01-15 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avtar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avtar',
            new_name='avatar',
        ),
    ]
